### ISSUE TITLE
Displays a list of Cards

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#1]
## Value proposition

As a user
I want to see a list of machines and their settings
in order to have an overview of them

## Description

![image](https://user-images.githubusercontent.com/94522570/236058715-c142edd8-b6a2-4ce5-8990-93dae453ae81.png)

## Acceptance criteria

- [x] each entry has its own card
- [x] each card displays the machine name
- [x] there is at least 1 setting on each card

## Tasks

- [x] create a branch
- [x] create initial data for cards
- [x] create a card component

       

Size: medium

**Comment by BenRodProd** [comment]
as every US should lead to an app with no loose ends, I suggest to add the add and delete button with the US where you create an add / a delete function... rest LGTM...

**Comment by mbosselmann** [comment]
Hi Granit,
great first user story! 💪 I have some remarks for you to consider:

## Description
- As Ben already suggested you should only implement components that have a functionality. Your start page would lead to parts of your app that are not implemented yet (goals and calorie tracker). These links should not be implemented for now. If then the user should be able to view a list of machines with the settings for each machine it is not necessary to have the start page. Just add it later when you want to get to the goals or calorie tracker.

## Acceptance criteria
- I like them! They already show that what is necessary here is the machine list and nothing else. :)

## Tasks
- I would remove the following tasks (see my comment above):
  - (create the "Navigation Page" with link/button to "Machine Settings" page)
  - buttons task
- I think the details for your card are not necessary. It would be enough to write "create a card component". :)

So try to reduce your user story! I am looking forward to your updated user story. :)

Feel free to ask if you have further questions. :octocat:

**Comment by frank12421** [comment]
Hi Granite, very well reduced. Looks good to me.
