### ISSUE TITLE
adding landing page

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#11]
## Value proposition

As a user
I want to choose which part of the app i want to use
in order to switch between machine settings list and nutrient tracker

## Description

![image](https://github.com/granitn/capstone-project/assets/94522570/cd802d83-0259-4327-92da-6a6b98ee0148)

## Acceptance criteria

- [x] there is a landing page 
- [x] there is a link on the page 
- [x] the link redirects to machine list page
- [x] there is a link back from list page to landing page

## Tasks

- [x] create a branch
- [x] change current index.js to list.js
- [x] build new index.js  
- [x] create link to list
- [x] add back link from list.js to index.js
- [x] add minor styling

Size: s

**Comment by CJAkkuec** [comment]
>  the second link redirects to a mostly empty, soon to be nutrient tracker

I don't think you should be directing people to an empty page. If the feature doesn't exist yet, it shouldn't be featured on the landing page. For the time being, you'd only include the Machine Settings and include the Nutrient Tracker once the feature is ready.

**Comment by granitn** [comment]
thank you,
appreciate your feedback.
i implemented the changes and hope ist fine now :)

**Comment by HenrikeStahlhut** [comment]
LGTM 🕺
