### ISSUE TITLE
Entering goals

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#12]
## Value proposition

As a user
I want to enter my goals
in order to have them displayed

## Description

![image](https://github.com/granitn/capstone-project/assets/94522570/8e2062b0-8842-422a-8ec4-516924383e5e)

## Acceptance criteria

- [x] there are three links on the index page
- [x] the second link leads to a form to enter the user goals
- [x] there are user set goals visible on the tracker page(kcal, carbs, protein, fat)
- [x] there is a back button (link) on the form page to cancel the process/get back to index page

## Tasks

- [x] create a branch
- [x] create "set your goals" link to goal form
- [x] make intakeForm usable for goals 
- [x] add checkbox on form to switch between kcal or macro goal
- [x] add link back to index 
- [x] save goal form data in local storage
- [x] display goals on tracker page (kcal: .../2800, protein: .../120g, etc.)

Size: m
