### ISSUE TITLE
Entering intake

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#13]
## Value proposition

As a user
I want to enter the nutrients i have eaten
in order to keep track of my intake

## Description

![image](https://github.com/granitn/capstone-project/assets/94522570/6cdf278a-81ac-4d0d-93be-f55f733ad1e8)

## Acceptance criteria
- [x] there is a tracker page
- [x] there is a back button (link) on the tracker page to get to the index page
- [x] on the tracker page there is a "I ate" button (link)
- [x] the button links to intake form
- [x] there is a back button(link) to cancel the process
- [x] the back button links to tracker page
- [x] Carbs, Protein, Fat inputs are required
- [x] form data is displayed on tracker page next to goals
- [x] dummy goals are visible on tracker page

## Tasks

- [x] create a branch
- [x] create tracker page
- [x] add link back to index
- [x] create intakeForm component
- [x] create intake page
- [x] add form data to local storage
- [x] make tracker page render intake values next to goal values 
- [x] create "I ate" link to intake page
- [x] add "back" link to tracker page

Size: L

**Comment by antoniatandler** [comment]
LGTM!
