### ISSUE TITLE
Displaying progress Bars

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#17]
## Value proposition

As a user
I want to have a visual display of my progress
in order to track my progress in a more appealing way

## Description

![image](https://github.com/granitn/capstone-project/assets/94522570/38048614-53e1-48da-af68-ed241c4812b2)

## Acceptance criteria

- [x] there is a progress bar for each value (kcal, carbs, protein, fat) displayed on the tracker page

## Tasks

- [x] create branch
- [x] implement react circular progress bar
- [x] modify component: try deleting text part
                                         changing width and color 
- [x] create 4 progress bars 
- [x] wire todaysIntake and goal to progress bar 

Size: m
