### ISSUE TITLE
Displaying small animation

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#19]
## Value proposition

As a user
I want to see a small animation upon each progress bar completion
in order to feel rewarded

## Description

![image](https://github.com/granitn/capstone-project/assets/94522570/48942e1e-73b9-4290-94fd-5f8025f67233)

## Acceptance criteria

- [x] a svg line appears above the Progressbars upon goal completion
- [x] there is a line representing each Progressbar

## Tasks

- [x] create a branch
- [x] install framer motion
- [x] set up const draw 
- [x] add motion.svg and motion.line to progressbarContainer 

Size: hopefully "s"

**Comment by doctype-Melvin** [comment]
🌈
