### ISSUE TITLE
Adding new machines

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#2]
## Value proposition

As a user
I want to add new machines
in order to expand my list of machines

## Description

![image](https://user-images.githubusercontent.com/94522570/236436086-11fc3aa8-74cb-48e0-b880-7fea000e6374.png)

## Acceptance criteria

- [x] there is an "Add" button on the machine settings page that leads to the form where new machines can be added
- [x] the form has the title "add new machine"
- [x] the form has one input field for the machine name 
- [x] the form has one text area input to enter different settings divided by line breaks
- [x] both inputs are required and labeled according to the expected entries
- [x] the form has a submit button
- [x] on submit the user is redirected to list page where the new entry is visible at the end of the list
- [x] the form page has a back button to cancel the process

## Tasks

- [x] create a branch
- [x] create a form component
- [x] create a form page and link to it through the "Add" button
- [x] create a POST route to database
- [x] make the input data accessible
- [x] add data to database

Size: medium

**Comment by JessicaLoers** [comment]
**Hey @granitn** ✌️
nice user story!   I have some suggestions for you to consider before moving forward.

## Value proposition
**As a user**
**I want to** add new machines
**in order to** expand my list of machines

➡️  _It is enough to mention that new machines will be added. The user doesn't really care that they are cards._

## Acceptance criteria

➡️  _Here are some suggestion to make your acceptance criteria more precisely. This will help you to work on this user story in a more targeted way._ 

- How the user gets to the form? 
	- e.g. An "Add" button on the machine settings page leads to a page with a form where new machines can be entered
- Describes everything about the form in more detail. 
	- What data is requested and which fields are visible? 
	- Wich inputs are required?
	- What happens if I, as a user, submit the form blank?
	- What happens when I have successfully submitted the form? Do I get a notice that my machine has been added or am I redirected back to the previous page?
- What exactly is the "Back" button for? Maybe to cancel the process?  
 Little side note🤓: _Please keep in mind that this button is not a real button, but a Next `<Link>`, that is often confused in many projects._ 

With regard to your extended criteria, you could also describe your tasks in more detail. 

**Please take some more time to improve this user story. It will help you a lot in the process - I promise**.🤞

**Comment by granitn** [comment]
Hi @JessicaLoers 
thank you,
I appreciate your feedback and tried implementing the changes you suggested

**Comment by mbosselmann** [comment]
Hi Granit,
great job! 💪 I can see that you invested some time to rethink this user story and you also added the points that we discussed today. Nevertheless, I have two nit-picking remarks for you that might be interesting for you:
- Your form could have a title for a better accessibility: Something like `Add new machine`
- And you could describe in your acceptance criteria if the new entry is visible below the already existing entries or whether the entry is the first place from the list

And I have one question: Is your database also available via MongoDB Atlas? This is necessary for the quality assurance for your test users (also for your first user story).

**Comment by granitn** [comment]
Hi Mareike,
thanks for your feedback.
I just added your suggestions to the user story.

regarding your question,
right now i'm only using the local database. So i would have to transfer my dataset over to atlas. 
should I do that while working on US 1 or create its own US for this change ?

**Comment by mbosselmann** [comment]
Hi Granit,
yay! :octocat: 

You should do that while working on your first US1 otherwise you have nothing to show in your QA. In your task list for user story 2 you should remove the word "local" and just to refer to the database. That is ok! 👍

I will approve your second user story now (so it is not necessary to post it again in our channel).

Happy hacking! :octocat:
