### ISSUE TITLE
Deleting machines 

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#4]
## Value proposition

As a user
I want to delete existing machine entries
in order to keep the list compact and remove those i don't use anymore

## Description

![image](https://user-images.githubusercontent.com/94522570/236800606-46ff8e0b-9065-46ef-b83c-8e68e8337b57.png)

## Acceptance criteria

- [x] there is a delete "(-)" button on each card
- [x] the button removes an entry from the list

## Tasks

- [x] create a branch
- [x] create a delete button component
- [x] add delete button to card component
- [x] write DELETE route 
- [x] write handle delete function
- [x] make _id available to delete function

Size: M
