### ISSUE TITLE
Editing existing machines

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#5]
## Value proposition

As a user
I want to edit existing entries
in order to correct possible misjudgments in the machine settings

## Description

![image](https://user-images.githubusercontent.com/94522570/236822691-615ced57-653e-4ccc-8991-6fd2725c05ee.png)

## Acceptance criteria

- [x] there is a edit (gear) button/Link on each card
- [x] clicking the edit(gear) button/Link redirects to the form page
- [x] the entries content can be changed
- [x] form shows existing entry inside input fields
- [x] the "submit" button redirects to the machine list

## Tasks

- [x] create a branch
- [x] create a "gear" button component 
- [x] add to card component
- [x] make form component reusable by lifting existing logic up 
  and passing down via props  
- [x] add "PUT" route
- [x] add handleSubmit function
- [x] add sendRequest function
- [x] make form show existing entry inside input fields

Size: L

**Comment by mbosselmann** [comment]
Hi Granit,
LGTM! 🦊 Just one remark: POST is for create and PUT is for update. That should be changed in your tasks. :)
Nevertheless, I will approve your user story. 💪

**Comment by granitn** [comment]
Thank you Mareike,
got all tangled up in crud and http methods 😵‍💫
made the changes immediately
